// SESSION
export const INVALIDATE_TOKEN = 'INVALIDATE_TOKEN';

// USERS
export const USER_BUSY_FETCHING_FROM_BACKEND = 'USER_BUSY_FETCHING_FROM_BACKEND';
export const USERS_FETCHED_FROM_BACKEND = 'USERS_FETCHED_FROM_BACKEND';
export const USERS_FETCH_FAILED_FROM_BACKEND = 'USERS_FETCH_FAILED_FROM_BACKEND';
export const USERS_APPLY_SORT = 'USER_APPLY_SORT';


export const USERS_MOVE_TO_PAGE = 'USERS_MOVE_TO_PAGE';
export const USERS_CHANGE_PER_PAGE_COUNT = 'USERS_CHANGE_PER_PAGE_COUNT';

export const USERS_UPDATE_FILTER = 'USERS_UPDATE_FILTER';

export const USERS_UPDATE_USER = 'USERS_UPDATE_USER';
export const USERS_DELETE_USER = 'USERS_DELETE_USER';
export const USERS_CREATED_USER = 'USERS_CREATED_USER';
